require('core.plugins_config.nvim-tree')
require('core.plugins_config.lualine')
require('core.plugins_config.sonokai')
require('core.plugins_config.haskell_tools')
require('core.plugins_config.lspconfig')
